services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./apps

    env_file:
      - .env

    ports:
      - "8080:3000"

    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
