apiVersion: apps/v1
kind: Deployment

metadata:
  name: homelab-web

spec:
  replicas: 1

  selector:
    matchLabels:
      app: homelab-web

  template:
    metadata:
      labels:
        app: homelab-web

    spec:
      containers:
        - name: web

          image: ghcr.io/msmidegas/homelab-web:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: homelab-web-config

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_HOST
              value: db

            - name: POSTGRES_PORT
              value: "5432"
