apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:

  - namespace.yaml

  - storage/postgres-pv.yaml
  - storage/postgres-pvc.yaml

  - postgres/postgres-secret.yaml
  - postgres/postgres.yaml
  
  - web/configmap.yaml
  - web/deployment.yaml
  - web/service.yaml

  - ingress.yaml
