apiVersion: v1
data:
  LOG_LEVEL: info
  NODE_ENV: production
  PORT: "3000"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"LOG_LEVEL":"info","NODE_ENV":"production","PORT":"3000"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"homelab-web-config","namespace":"default"}}
  creationTimestamp: "2026-07-08T15:50:30Z"
  name: homelab-web-config
  namespace: default
  resourceVersion: "17279"
  uid: 08d19b86-23b3-4501-99c6-61876cc82e11
