apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"db","namespace":"default"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"postgres"}}}
    creationTimestamp: "2026-07-03T14:01:53Z"
    name: db
    namespace: default
    resourceVersion: "1711"
    uid: adf1bea7-f7ef-4224-938b-38b29badf073
  spec:
    clusterIP: 10.43.229.74
    clusterIPs:
    - 10.43.229.74
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"homelab-web-service","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":3000}],"selector":{"app":"homelab-web"},"type":"NodePort"}}
    creationTimestamp: "2026-07-03T13:46:52Z"
    name: homelab-web-service
    namespace: default
    resourceVersion: "904"
    uid: fca796ab-3041-489e-8190-8e00302bc8a1
  spec:
    clusterIP: 10.43.124.103
    clusterIPs:
    - 10.43.124.103
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32709
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: homelab-web
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-07-03T13:41:31Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "202"
    uid: 64f184b0-281f-4395-bfee-45e4c08bc0ac
  spec:
    clusterIP: 10.43.0.1
    clusterIPs:
    - 10.43.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
