name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug GitHub Secrets
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          echo "===== DEBUG ====="
          echo "POSTGRES_USER=$POSTGRES_USER"
          echo "POSTGRES_DB=$POSTGRES_DB"
          echo "POSTGRES_PASSWORD length=${#POSTGRES_PASSWORD}"
          echo "================="

      - name: Deploy
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: docker compose up -d --build
